export const customerData = [
    {
        id: 1,
        img: "https://www.getharvest.com/hubfs/customers/rana/rana-logo.svg",
        category:"Architecture",
        desc: "Rana, an ecological design company, uses Harvest to keep track of their projects and billable hours in one place.",
      },
      {
        id: 2,
        img: "https://www.getharvest.com/hubfs/customers/centric-digital/tras.svg",
        category:"Productivity",
        desc: "Digital transformation company Centric Digital relies on Harvest’s reports and invoicing.",
      },
      {
        id: 3,
        img: "https://www.getharvest.com/hubfs/customers/mutual-mobile/mutual-mobile-logo.svg",
        category:"Productivity",
        desc: "Harvest supported mobile development agency Mutual Mobile in their recent growth.",
      },
      {
        id: 4,
        img: "https://www.getharvest.com/hubfs/public-logo.svg",
        category:"Architecture",
        desc: "An architecture firm focused on the public realm uses Harvest to keep fixed-fee projects profitable.",
      },
      {
        id: 5,
        img: "https://www.getharvest.com/hubfs/customers/hashrocket/hashrocket-logo.svg",
        category:"Web development & IT",
        desc: "Design &amp; development agency Hashrocket uses timers to track time throughout their day.",
      },
      {
        id: 6,
        img: "https://www.getharvest.com/hubfs/cooper-perkins/logo-cooper-perkins.svg",
        category:"Engineering & design",
        desc: "Engineering practice Cooper Perkins uses Harvest to project future needs.",
      },
      {
        id: 7,
        img: "https://www.getharvest.com/hubfs/customers/logo-dovetail.svg",
        category:"Web development & IT",
        desc: "Startup studio Dovetail tracks time with Harvest to build trust with clients.",
      },
      {
        id: 8,
        img: "https://www.getharvest.com/hubfs/luminary-labs/logo-index-luminarylabs-0fe6b11e1f976e648dc6907ba9a2a677a71ed9013820ed9dba0415aaa4c6bd5a-1.svg",
        category:"Management consulting",
        desc: "Strategy &amp; innovation consultancy Luminary Labs manages team utilization with Harvest..",
      },
      {
        id: 9,
        img: "https://www.getharvest.com/hubfs/customers/tekna/tekna-logo.svg",
        category:"Engineering & design",
        desc: "Harvest helps product design company Tekna save time by streamlining their process.",
      },
      {
        id: 10,
        img: "https://www.getharvest.com/hubfs/customers/thecharles/the-charles-logo.svg",
        category:"Creative services",
        desc: "The Charles uses time tracking to reinforce client and employee happiness.",
      },
      {
        id: 11,
        img: "https://www.getharvest.com/hubfs/customers/clinovations/clinovations-logo-1.svg",
        category:"Management consulting",
        desc: "Healthcare strategists Clinovations streamlined their time tracking with Harvest.",
      },
      {
        id: 12,
        img: "https://www.getharvest.com/hubfs/customers/turnstyle/turnstyle-logo.svg",
        category:"Creative services",
        desc: "Harvest enables design agency Turnstyle to stay mindful of smart business practices.",
      },
      {
        id: 13,
        img: "https://www.getharvest.com/hubfs/customers/vayner-media/vayner-media-logo.svg",
        category:"Creative services",
        desc: "Consulting agency VaynerMedia uses Harvest to surface patterns and opportunities.",
      },
      {
        id: 14,
        img: "https://www.getharvest.com/hubfs/customers/yld/yld-logo-1.svg",
        category:"Web development & IT",
        desc: "Engineering consultancy YLD relies on Harvest to plan, staff, and manage their projects.",
      },
      {
        id: 15,
        img: "https://www.getharvest.com/hubfs/customers/juicyorange/juicyorange-logo-2.svg",
        category:"Web development & IT",
        desc: "Harvest helps web design company Juicyorange justify their pricing.",
      },
      {
        id: 16,
        img: "https://www.getharvest.com/hubfs/customers/area-17/area-17-logo.svg",
        category:"Creative services",
        desc: "Interactive design agency Area 17 checks Harvest reports to keep tabs on their business.",
      },
      {
        id: 17,
        img: "https://www.getharvest.com/hubfs/adamick/adamick-logo.svg",
        category:"Architecture",
        desc: "Harvest helps Adamick Architecture speed up invoicing and increase profitability.",
      },
      {
        id: 18,
        img: "https://www.getharvest.com/hubfs/customers/ccd-innovation/ccd-logo-1.svg",
        category:"Creative services",
        desc: "Harvest helped culinary company CCD innovation step up their operational efficiency",
      },
      {
        id: 19,
        img: "https://www.getharvest.com/hubfs/customers/zehner/zehner-logo.svg",
        category:"Web development & IT",
        desc: "Digital agency Zehner manages their team’s bandwidth with Harvest.",
      },
      {
        id: 20,
        img: "https://www.getharvest.com/hubfs/customers/crossley-acoustics/crossley-acoustics-logo.svg",
        category:"Engineering & design",
        desc: "Acoustic design firm Crossley Acoustics uses Harvest to track time from job sites.",
      },
         
]