export const integrateData = [
    {
        id: 1,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/asana.png?width=300&name=asana.png",
        title: "Asana",
        category:"Featured integrations",
        desc: "Track time to Harvest without leaving Asana",
      },
      {
        id: 2,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/basecamp.png?width=300&name=basecamp.png",
        title: "Basecamp",
        category:"Featured integrations",
        desc: "Track your time without leaving Basecamp",
      },
      {
        id: 3,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/github.png?width=300&name=github.png",
        title: "GitHub",
        category:"Featured integrations",
        desc: "Track time to Harvest without leaving GitHub",
      },
      {
        id: 4,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/slack.png?width=300&name=slack.png",
        title: "Slack",
        category:"Communication & CRM",
        desc: "Make time tracking part of your team’s conversation",
      },
      {
        id: 5,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations/coupler-logo.png?width=300&name=coupler-logo.png",
        title: "Coupler",
        category:"Analytics & reporting",
        desc: "Export Harvest data to Google Sheets, Excel, and BigQuery",
      },
      {
        id: 6,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations/databox-icon@2x.png?width=300&name=databox-icon@2x.png",
        title: "Databox",
        category:"Analytics & reporting",
        desc: "Combine data from Harvest and other tools to create custom KPI dashboards.",
      },
      {
        id: 7,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations/eazybi-icon@2x.png?width=300&name=eazybi-icon@2x.png",
        title: "Eazybi",
        category:"Analytics & reporting",
        desc: "Harvest timesheet reporting, interactive drag-and-drop charts, and dashboards.",
      },
      {
        id: 8,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/stripe.png?width=300&name=stripe.png",
        title: "Stripe",
        category:"Finance & payments",
        desc: "Accept online payments from your clients",
      },
      {
        id: 9,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/paypal.png?width=300&name=paypal.png",
        title: "Paypal",
        category:"Finance & payments",
        desc: "Accept online payments from your clients",
      },
      {
        id: 10,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/chrome.png?width=300&name=chrome.png",
        title: "Chrome",
        category:"Browser extensions",
        desc: "Track time to Harvest from the Chrome toolbar.",
      },
      {
        id: 11,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations/donedone-icon@2x.png?width=300&name=donedone-icon@2x.png",
        title: "Donedone",
        category:"Issue tracking & support",
        desc: "Track time in Harvest as you track your work.",
      },
      {
        id: 12,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/freshservice.png?width=300&name=freshservice.png",
        title: "Freshservice",
        category:"Issue tracking & support",
        desc: "Generate custom invoices and letters with your Harvest data.",
      },
      {
        id: 13,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/jira.png?width=300&name=jira.png",
        title: "Jira",
        category:"Issue tracking & support",
        desc: "Track time right from the issue and project tracking software Jira.",
      },
      {
        id: 14,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/zendesk.png?width=300&name=zendesk.png",
        title: "Zendesk",
        category:"Issue tracking & support",
        desc: "A professional help desk tool where you can track time spent on tickets for billing.",
      },
      {
        id: 15,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/alfred.png?width=300&name=alfred.png",
        title: "Alfred",
        category:"Productivity",
        desc: "Track time to Harvest without leaving Trello",
      },
      {
        id: 16,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations/klipfolio-icon@2x.png?width=300&name=klipfolio-icon@2x.png",
        title: "Klipfolio",
        category:"Issue tracking & support",
        desc: "Seamlessly copy Harvest invoices to QuickBooks Online",
      },
      {
        id: 17,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/edge.png?width=300&name=edge.png",
        title: "Edge",
        category:"Browser extensions",
        desc: "Track time right from your browser and popular project management tools.",
      },
      {
        id: 18,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/firefox.png?width=300&name=firefox.png",
        title: "FireFox",
        category:"Browser extensions",
        desc: "Track time right from your browser and popular project management tools.",
      },
      {
        id: 19,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations/akita-icon@2x.png?width=300&name=akita-icon@2x.png",
        title: "Akita",
        category:"Communication & CRM",
        desc: "View a complete project and invoice history for each Harvest client.",
      },
      {
        id: 20,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/workspace.png?width=300&name=workspace.png",
        title: "GoogleWorkspace",
        category:"Communication & CRM",
        desc: "Sign in with your Google account and export time data into Google Drive.",
      },
      {
        id: 21,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations/bidsketch-icon@2x.png?width=300&name=bidsketch-icon@2x.png",
        title: "Bidsketch",
        category:"Contracts & proposals",
        desc: "Create and track beautiful proposals, which can then be invoiced from Harvest.",
      },
      {
        id: 22,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/formstack.png?width=300&name=formstack.png",
        title: "Formstack",
        category:"Contracts & proposals",
        desc: "Generate custom invoices and letters with your Harvest data.",
      },
      {
        id: 23,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations/coupler-logo.png?width=300&name=coupler-logo.png",
        title: "Coupler",
        category:"Development & connectivity",
        desc: "Export Harvest data to Google Sheets, Excel, and BigQuery",
      },
      {
        id: 24,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations/databox-icon@2x.png?width=300&name=databox-icon@2x.png",
        title: "Databox",
        category:"Development & connectivity",
        desc: "Combine data from Harvest and other tools to create custom KPI dashboards.",
      },
     
    
    
    
      
]