export const integrateData = [
    {
        id: 1,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/asana.png?width=300&name=asana.png",
        title: "Asana",
        desc: "Track time to Harvest without leaving Asana",
      },
      {
        id: 2,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/basecamp.png?width=300&name=basecamp.png",
        title: "Basecamp",
        desc: "Track your time without leaving Basecamp",
      },
      {
        id: 3,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/github.png?width=300&name=github.png",
        title: "GitHub",
        desc: "Track time to Harvest without leaving GitHub",
      },
      {
        id: 4,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/slack.png?width=300&name=slack.png",
        title: "GitHub",
        desc: "Make time tracking part of your team’s conversation",
      },
      {
        id: 5,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/trello.png?width=300&name=trello.png",
        title: "GitHub",
        desc: "Track time to Harvest without leaving Trello",
      },
      {
        id: 6,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/qbo.png?width=300&name=qbo.png",
        title: "GitHub",
        desc: "Seamlessly copy Harvest invoices to QuickBooks Online",
      },
      {
        id: 7,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/xero.png?width=300&name=xero.png",
        title: "GitHub",
        desc: "Automatically copy Harvest invoices to Xero",
      },
      {
        id: 8,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/stripe.png?width=300&name=stripe.png",
        title: "Stripe",
        desc: "Accept online payments from your clients",
      },
      {
        id: 9,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/paypal.png?width=300&name=paypal.png",
        title: "Paypal",
        desc: "Accept online payments from your clients",
      },
      {
        id: 10,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/chrome.png?width=300&name=chrome.png",
        title: "Chrome",
        desc: "Track time to Harvest from the Chrome toolbar.",
      },
      {
        id: 11,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/asana.png?width=300&name=asana.png",
        title: "Asana",
        desc: "Track time to Harvest without leaving Asana",
      },
      {
        id: 12,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/basecamp.png?width=300&name=basecamp.png",
        title: "Basecamp",
        desc: "Track your time without leaving Basecamp",
      },
      {
        id: 13,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/github.png?width=300&name=github.png",
        title: "GitHub",
        desc: "Track time to Harvest without leaving GitHub",
      },
      {
        id: 14,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/slack.png?width=300&name=slack.png",
        title: "GitHub",
        desc: "Make time tracking part of your team’s conversation",
      },
      {
        id: 15,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/trello.png?width=300&name=trello.png",
        title: "GitHub",
        desc: "Track time to Harvest without leaving Trello",
      },
      {
        id: 16,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/qbo.png?width=300&name=qbo.png",
        title: "GitHub",
        desc: "Seamlessly copy Harvest invoices to QuickBooks Online",
      },
      {
        id: 17,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/xero.png?width=300&name=xero.png",
        title: "GitHub",
        desc: "Automatically copy Harvest invoices to Xero",
      },
      {
        id: 18,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/stripe.png?width=300&name=stripe.png",
        title: "Stripe",
        desc: "Accept online payments from your clients",
      },
      {
        id: 19,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/paypal.png?width=300&name=paypal.png",
        title: "Paypal",
        desc: "Accept online payments from your clients",
      },
      {
        id: 20,
        img: "https://www.getharvest.com/hs-fs/hubfs/integrations-new/chrome.png?width=300&name=chrome.png",
        title: "Chrome",
        desc: "Track time to Harvest from the Chrome toolbar.",
      },
]